### ISSUE TITLE
Can it use the openai api?

### ISSUE THREAD

**Issue by GuodongFan** [Shark-NLP/OpenICL#10]
such as gpt-3 4

**Comment by numbmelon** [comment]
yep, you can find some helpful information in [tutorial2](https://github.com/Shark-NLP/OpenICL/blob/main/examples/tutorials/openicl_tutorial2_use_different_models.ipynb).But currently only the interface of gpt3 is implemented, chatgpt api and many more interfaces may be coming in the next week :)
