### ISSUE TITLE
How to add definition and constraint?

### ISSUE THREAD

**Issue by GuodongFan** [Shark-NLP/OpenICL#13]
How to add definition and constraint besides example?

**Comment by yxwang8775** [comment]
Could you please clarify what you mean by 'definition' and 'constraint'? If you mean add constraints to model.generate(), you may set 'generation_kwargs' of the GenInferencer following https://huggingface.co/docs/transformers/main/en/main_classes/text_generation.

**Comment by GuodongFan** [comment]
The current prompt only uses the top-k examples, but I want to restrict the output space of the results and give some general context knowledge. For example, 

prompt= '''
Model select inteion from (A, B, C)\n
example 0 \t A \n
example 1 \t B \n
example x \t
'''

**Comment by GuodongFan** [comment]
great! thanks.
