### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by Hannibal046** [Shark-NLP/OpenICL#15]
Hi, thanks for the work!

After install the OpenICL (either through pip or from source), I got the following error when trying the command `python test/test_flores101.py` in this repo https://github.com/OwenNJU/MMT-LLM

```
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
cannot import name 'PartialState' from 'accelerate' (/anaconda/envs/mmt/lib/python3.8/site-packages/accelerate/__init__.py)
```

**Comment by Dereck0602** [comment]
Hello, I have also encountered this issue. Do you have any solutions to the problem?

**Comment by yxwang8775** [comment]
Maybe you could try:
pip install --upgrade accelerate

**Comment by Hannibal046** [comment]
Sorry, my mistake. I think the problem is in https://github.com/OwenNJU/MMT-LLM rather than `OpenICL`. 
`MMT-LLM` uses a hacked version of `OpenICL`. Maybe their code currently is not fully ready.

BTW, `Accelerate` introduces `PartialState` in `0.17` version.
