### ISSUE TITLE
template share?

### ISSUE THREAD

**Issue by fzp0424** [Shark-NLP/OpenICL#16]
Hi, thanks for the work! The whole framework is easy to use!

I am reproducing some work in the paper and I want to know the standard rules of building a template, like PIQA and other types of NLP tasks

**Comment by fzp0424** [comment]
> you can find information about `PromptTemplate` at [tutorial 1](https://github.com/Shark-NLP/OpenICL/blob/main/examples/tutorials/openicl_tutorial1_getting_started.ipynb) and some examples at [example](https://github.com/Shark-NLP/OpenICL/blob/main/examples/research_projects/self-adaptive_in-context_learning.ipynb).
> 
> for PIQA, The configuration in our paper is as follows (using PPL inference strategy)：
> 
> ```python
> DATASET=load_dataset('piqa')
> DATASETREADER=DatasetReader(DATASET, input_columns=['goal', 'sol1', 'sol2'], output_column='label')
> TEMPLATE=PromptTemplate(
>     {
>         0: "</E>Sentence: </G>\n\nChoice </S1>: sol1\n\nChoice </S2>: sol2\n\nWhat is the index of the correct choice for ending for the sentence?\n\nAnswer: sol1",
>         1: "</E>Sentence: </G>\n\nChoice </S1>: sol1\n\nChoice </S2>: sol2\n\nWhat is the index of the correct choice for ending for the sentence?\n\nAnswer: sol2"
>     },
>     column_token_map={'sol1':'</S1>', 'sol2':'</S2>', 'goal':'</G>'},
>     ice_token='</E>' 
> )
> ```
> 
> note that in our paper we only show the effectiveness of the system. These templates are not necessarily optimal.
> 
> generally speaking, there are no standard rules for template construction. You can look at the templates in other papers, or conduct some comparative experiments

Thanks for your reply and suggestions!

**Comment by numbmelon** [comment]
set `ice_num=8` in `TopkRetriever`. 

for LM, using `EleutherAI/gpt-neo-2.7B` (or maybe `gpt2-xl`)

no more details.

There is not much difference between PPL and channel, i think PPL is easier and better in most cases, maybe something else went wrong?

**Comment by fzp0424** [comment]
> > > set `ice_num=8` in `TopkRetriever`.
> > > for LM, using `EleutherAI/gpt-neo-2.7B` (or maybe `gpt2-xl`)
> > > no more details.
> > > There is not much difference between PPL and channel, i think PPL is easier and better in most cases, maybe something else went wrong?
> > 
> > 
> > yes, the code is simple, but I don't know what the problem is...
> > ```
> > import os
> > from datasets import load_dataset
> > from openicl import DatasetReader, PromptTemplate, TopkRetriever, PPLInferencer, AccEvaluator, VotekRetriever, MDLRetriever, ChannelInferencer
> > 
> > os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   
> > os.environ["CUDA_VISIBLE_DEVICES"]="2"         # specify the GPU you want to use
> > ice_num = 8
> > print("ice_num:", ice_num)
> > 
> > # Loading dataset from huggingface
> > dataset=load_dataset('piqa')
> > data=DatasetReader(dataset, input_columns=['goal', 'sol1', 'sol2'], output_column='label',test_split='test')
> > template=PromptTemplate(
> >     {
> >         0: "</E>Sentence: </G>\n\nChoice </S1>: sol1\n\nChoice </S2>: sol2\n\nWhat is the index of the correct choice for ending for the sentence?\n\nAnswer: sol1",
> >         1: "</E>Sentence: </G>\n\nChoice </S1>: sol1\n\nChoice </S2>: sol2\n\nWhat is the index of the correct choice for ending for the sentence?\n\nAnswer: sol2"
> >     },
> >     column_token_map={'sol1':'</S1>', 'sol2':'</S2>', 'goal':'</G>'},
> >     ice_token='</E>' 
> > )
> > 
> > retriever = TopkRetriever(data, ice_num = ice_num, index_split='train', test_split='test')
> > 
> > inferencer = PPLInferencer(model_name='gpt2-xl',output_json_filename='piqa-gpt2-xl')
> > 
> > predictions = inferencer.inference(retriever, ice_template=template)
> > 
> > score = AccEvaluator().score(predictions=predictions, references=data.references)
> > 
> > print(score)```
> > ```
> 
> we test on validation set, [test set](https://huggingface.co/datasets/piqa/viewer/plain_text/test?p=1) of piqa has no label.
> 
> just change your `test_split` in `DatasetReader` and `Retriever`

The result of validation set is around 0.48

**Comment by numbmelon** [comment]
sorry for providing you with the incorrect template,please try this one:
```python
template=PromptTemplate(
    {
        0: "</E>\nQuestion: </G>\nAnswer: </S1>",
        1: "</E>\nQuestion: </G>\nAnswer: </S2>"
    },
    column_token_map={'sol1':'</S1>', 'sol2':'</S2>', 'goal':'</G>'},
    ice_token='</E>' 
)
```
I tested it on gpt2-xl, the accuracy  is 73.83%, here is the complete code for you:
```python
import os
from datasets import load_dataset
from openicl import DatasetReader, PromptTemplate, TopkRetriever, PPLInferencer, AccEvaluator, VotekRetriever, MDLRetriever, ChannelInferencer

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   
os.environ["CUDA_VISIBLE_DEVICES"]="2"         # specify the GPU you want to use
ice_num = 8
print("ice_num:", ice_num)

# Loading dataset from huggingface
dataset=load_dataset('piqa')
data=DatasetReader(dataset, input_columns=['goal', 'sol1', 'sol2'], output_column='label',test_split='validation')
template=PromptTemplate(
    {
        0: "</E>\nQuestion: </G>\nAnswer: </S1>",
        1: "</E>\nQuestion: </G>\nAnswer: </S2>"
    },
    column_token_map={'sol1':'</S1>', 'sol2':'</S2>', 'goal':'</G>'},
    ice_token='</E>' 
)

retriever = TopkRetriever(data, ice_num = ice_num, index_split='train', test_split='validation')

inferencer = PPLInferencer(model_name='gpt2-xl',output_json_filename='piqa-gpt2-xl')

predictions = inferencer.inference(retriever, ice_template=template)

score = AccEvaluator().score(predictions=predictions, references=data.references)

print(score)
```
