### ISSUE TITLE
the usage of tokenizer in icl_topk_retriever.py

### ISSUE THREAD

**Issue by mrzhang11** [Shark-NLP/OpenICL#18]
Hi, thank you for the nice codebase!

I have a question regarding the usage of tokenizer (e.g., tokenizer_name='gpt2-xl') in the TopkRetriever. 

As the sentence transformers have the "encode()" function which directly accepts the raw text as input (line 113), I was wondering, is there any particular reason that you encode the text first by using the DatasetEncoder (e.g., line 82), and then decode it again (e.g., line 112)?

Thank you in advance!

**Comment by yxwang8775** [comment]
This is a choice made for compatibility when integrating the code. Since it does not affect the normal operation of the code, no optimization is done here.
