### ISSUE TITLE
Is it possible to use this codebase to further fine-tuning(warmup) LLMs to obtain better ICL capability?

### ISSUE THREAD

**Issue by Thedatababbler** [Shark-NLP/OpenICL#20]
First of all, thank you for this awesome repository. It makes things ten times easier to test a model's in context learning power. I've been trying to fine-tune some LLMs to 'warmup' its capability of ICL, however, I found it is hard to find a mature codebase to do that. I've tried MetaICL's codebase, but I found downloading datasets is really painful for that model. So I wonder, is it possible to use openICL to do further fine-tuning for the LLMs? If there is a way to do so, would you mind to give me an example script or tutorial on how to do the fine-tuning? Thanks a lot.

**Comment by yxwang8775** [comment]
Sorry, our framework does not support direct fine-tuning, but you can load your own fine-tuned model.
