### ISSUE TITLE
SNLI template in tutorial

### ISSUE THREAD

**Issue by Thedatababbler** [Shark-NLP/OpenICL#21]
Hi, I have been reading your tutorial about how to use template recently. And I noticed that for the example of using 'snli' dataset. The tutorial have the following code:
```
# Define a DatasetReader, loading dataset from huggingface and selecting 10 pieces of data randomly.
data = DatasetReader('snli', input_columns=['premise', 'hypothesis'], output_column='label', ds_size=10)

# SNLI Template
tp_str = '</E>Premise:</premise>\nHypothesis:</hypothesis>\nDoes the premise entail the hypothesis?\nOPTIONS:\n-yes -It is not possible to tell -no'
template = PromptTemplate(tp_str, column_token_map={'premise' : '</premise>', 'hypothesis' : '</hypothesis>'}, ice_token='</E>')
```
We can see in the template tp_str, you did not include any label information in the template, only a templated OPTIONS information instead. That doesn't meet the use of In-context learning in my opinion, since ICL requires a 'question-answer' demonstration in the context. However, in this template, you only provide the 'premise' and 'hypothesis' but not the 'label' in the context. That doesn't make sense.

**Comment by yxwang8775** [comment]
In fact, the label here can be displayed in the in-context example. Only in the last sample that needs to be predicted, this label needs to be predicted by the model.
