### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by K1yomi** [Shark-NLP/OpenICL#4]
some problems when i use api, and I've entered my apikey into the terminal
![image](https://user-images.githubusercontent.com/78726603/225485800-3f6ebf1d-56ec-47ce-9740-c9e2d3bc8b9a.png)

**Comment by numbmelon** [comment]
I'm sorry, it looks like a bug. When calling the api, if  `max_model_token_num` is set, there will indeed not be an initialized `tokenizer` to check. I will fix this after I take a closer look at the gpt3 API calculation for tokens.

**Comment by numbmelon** [comment]
In OpenAI's GPT3 API, `max_tokens` is used to control the maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the completion. However, there is currently no official gpt3 tokenizer for us to use in python code to detect the length of the input token and decide whether to truncate it ([GPT-3-Encoder](https://github.com/latitudegames/GPT-3-Encoder) seems to implement the tokenzier of gpt3 and make it a JavaScript interface, i am not sure if this helpful). Maybe in the future we will implement this tokenizer, but until then, I will disable input token length detection for gpt3 in the main branch. 😔
