### ISSUE TITLE
Enable multi-gpu inference

### ISSUE THREAD

**Issue by BlackieMia** [Shark-NLP/OpenICL#6]
When inferencing with larger models (tens/hundreds of Billions of parameters), using a single GPU will run out of memory. Is it possible to load models with multiple GPUs?

**Comment by numbmelon** [comment]
Yes, we have already implemented this feature in `Inferencer`,  just set `model_parallel` to 'True'. However, for different models, some more parameters may still need to be passed in. Our implementation is based on Huggingface Accelerate, You need a `device_map` to map each component of the model (If this parameter is not passed in, an automatic mapping relationship will be generated. But some structures, such as the residual connections, cannot be separated) . Currently, you can directly pass in a `device_map` for `Inferencer`, or add some additional constraints like ```no_split_module_classes=["OPTDecoderLayer"]``` for opt-30b.

**Comment by numbmelon** [comment]
Sorry to bother you. I will add a related tutorial this week, or further improve this feature.

**Comment by BlackieMia** [comment]
Thanks very much for your explanation!
